# Generated by Django 5.2.3 on 2025-07-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='user_roles',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(choices=[('E1', 'E1'), ('E2', 'E2'), ('P1', 'P1'), ('P2', 'P2'), ('C3', 'C3'), ('C4', 'C4'), ('Agora', 'Agora'), ('E3', 'E3'), ('C3-Room', 'C3-Room'), ('C3-Relax', 'C3-Relax'), ('C4-rooms', 'C4-rooms'), ('Elevator-room', 'Elevator-room')], max_length=50),
        ),
    ]
