# Generated by Django 5.2.4 on 2025-07-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_pending_invites_location_choices'),
        ('events', '0002_events_user_roles_alter_events_location'),
    ]

    operations = [
    ]
