# Generated by Django 5.2.3 on 2025-06-22 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tracks', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('could_edit', models.JSONField(default=list)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_playlists', to='users.user')),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_playlists', to='users.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='users.user')),
            ],
            options={
                'db_table': 'playlists',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['owner'], name='playlists_owner_i_461bb0_idx'), models.Index(fields=['is_public'], name='playlists_is_publ_21b8cd_idx')],
            },
        ),
    ]
