# Generated by Django 5.2.4 on 2025-07-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='pending_invites',
            field=models.JSONField(default=list),
        ),
    ]
