package com.example.musicroom.data.auth

import android.content.Context
import android.content.SharedPreferences
import android.util.Log
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.asSharedFlow
import java.security.GeneralSecurityException
import javax.inject.Inject
import javax.inject.Singleton

private const val AUTH_PREFS_NAME = "auth_prefs"

@Singleton
class TokenManager @Inject constructor(
    @ApplicationContext private val context: Context
) {
    private val _sessionExpired = MutableSharedFlow<Unit>(extraBufferCapacity = 1)
    /** Emits when an authenticated API call comes back 401, meaning the stored token is dead. */
    val sessionExpired: SharedFlow<Unit> = _sessionExpired.asSharedFlow()

    private val masterKey = MasterKey.Builder(context)
        .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
        .build()

    // The Keystore-backed master key can end up out of sync with the encrypted prefs blob
    // (key regenerated by the OS, app data partially wiped/restored, etc.), which makes
    // decryption throw AEADBadTagException and crashes the app on every launch since this
    // runs during Activity creation. Self-heal by wiping the unreadable file and starting
    // over - the user just has to log in again, instead of the app being permanently bricked.
    private val sharedPreferences: SharedPreferences = createEncryptedPrefsOrReset()

    private fun createEncryptedPrefsOrReset(): SharedPreferences {
        return try {
            createEncryptedPrefs()
        } catch (e: Exception) {
            if (e is GeneralSecurityException || e is java.io.IOException) {
                Log.e("TokenManager", "⚠️ Encrypted prefs unreadable, resetting: ${e.message}")
                context.deleteSharedPreferences(AUTH_PREFS_NAME)
                createEncryptedPrefs()
            } else {
                throw e
            }
        }
    }

    private fun createEncryptedPrefs(): SharedPreferences = EncryptedSharedPreferences.create(
        context,
        AUTH_PREFS_NAME,
        masterKey,
        EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
        EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
    )

    // Separate, unencrypted, plain prefs for app-lifetime (not auth-lifetime) flags like
    // onboarding - keeping it out of `sharedPreferences` means clearTokens()/logout never
    // resets it.
    private val appPrefs: SharedPreferences =
        context.getSharedPreferences("app_prefs", Context.MODE_PRIVATE)

    fun saveToken(token: String) {
        sharedPreferences.edit().putString("auth_token", token).apply()
    }

    fun getToken(): String? {
        return sharedPreferences.getString("auth_token", null)
    }

    fun saveRefreshToken(refreshToken: String) {
        sharedPreferences.edit().putString("refresh_token", refreshToken).apply()
    }

    fun getRefreshToken(): String? {
        return sharedPreferences.getString("refresh_token", null)
    }

    fun clearTokens() {
        sharedPreferences.edit().clear().apply()
    }

    fun isLoggedIn(): Boolean {
        return getToken() != null
    }

    /** Call when an authenticated request fails with 401: clears the dead token and signals the UI to prompt a fresh login. */
    fun notifySessionExpired() {
        clearTokens()
        _sessionExpired.tryEmit(Unit)
    }

    fun hasSeenOnboarding(): Boolean {
        return appPrefs.getBoolean("has_seen_onboarding", false)
    }

    fun setOnboardingSeen() {
        appPrefs.edit().putBoolean("has_seen_onboarding", true).apply()
    }
}